name: Testing installers

on:
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set permissions
        run: chmod 755 install.sh
      
      - name: Run install script
        run: ./install.sh
      
      - name: Check installation
        run: |
          which nvm
          which yarn
          which git
          which google-chrome
